name: GitHub Metadata action
description: GitHub Metadata Action for Docker Buildx Bake.
author: Docker Baker

branding:
  color: white
  icon: git-branch

outputs:
  bake-file:
    description: Bake definiton file
    value: ${{ steps.meta.outputs.bake-file }}

runs:
  using: composite
  steps:
    - id: meta
      shell: bash
      run: |
        echo "::set-output name=bake-file::${GITHUB_ACTION_PATH}github-metadata-action.hcl"
    - name: Bake definition
      shell: bash
      run: |
        docker buildx bake -f "${GITHUB_ACTION_PATH}github-metadata-action.hcl" --print github-metadata-action
