name: GitHub Metadata action
description: GitHub Metadata Action for Docker Buildx Bake.
author: Docker Baker

branding:
  color: white
  icon: git-branch

outputs:
  bake-file:
    description: Bake definiton file
    value: ${{ steps.meta.outputs.bake-file }}

runs:
  using: composite
  steps:
    - id: meta
      name: GitHub Metadata action
      shell: bash
      run: |
        echo "::group::Processing GitHub context"
        echo "::set-output name=bake-file::${GITHUB_ACTION_PATH}/github-metadata-action.hcl"
        echo "::endgroup::"

        echo "::group::Bake definition"
        docker buildx bake -f "${GITHUB_ACTION_PATH}/github-metadata-action.hcl" --print github-metadata-action
        echo "::endgroup::"
