name: test

on:
  push:
    branches:
      - 'main'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Test runs
        id: meta
        uses: ./

      - name: Action output
        run: |
          echo "${{ steps.meta.outputs.bake-file }}"

      - name: Validate
        run: |
          docker buildx bake -f "${{ steps.meta.outputs.bake-file }}" --print github-metadata-action
